language: node_js
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
node_js:
- stable
os:
- linux
script:
- set -e
- yarn run build
- set +e
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
